
spring.application.name=student-app

spring.datasource.url=jdbc:postgresql://localhost:5432/studentsDB
spring.datasource.username=postgres
spring.datasource.password=Gnp2003@278

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true